############
# Makefile #
# ##########
#
# @author Alena Tesarova
# @date 28.03.2018
# IPK - 2. projekt, zadani II.
#
# ###############################

all: ipk-dhcpstarve

ipk-dhcpstarve: ipk-dhcpstarve.c
	gcc -Wall ipk-dhcpstarve.c  -o ipk-dhcpstarve

clean:
	rm -rf *.o ipk-dhcpstarve
