# FLP - 2nd project
# 04/2020
# Author: Bc. Alena Tesarova, xtesar36@stud.fit.vutbr.cz

PROGRAM=flp20-log
SRC=flp20-log.pl

CC=swipl
FLAGS=-q

all:
	$(CC) $(FLAGS) -g prolog -o $(PROGRAM) -c $(SRC)

clean:
	rm $(PROGRAM)
