<!--<div class = "container_fluid first_info">
    <div class = "text_info">
        <h2>WAWE</h2>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
            Fusce wisi. Integer lacinia. Suspendisse nisl. Temporibus autem quibusdam et aut officiis debitis aut rerum
            necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. </p>
        <label class = "vetsi_pismo">ID rezervace:</label>    
            
        <form method = "GET">
                        <p></p>
            <button class = "red_but">ZOBRAZIT REZERVACI</button>
            <input type="text" class="form-control" name="id_rezervace" placeholder="Vaše ID rezervace" id="id_rezervace2">
              <button class="btn btn-primary" >Zobrazit</button> 
            
        </form>
    </div>
</div>

-->

  <div class="py-5 text-center text-md-right" style="	background-image: linear-gradient(to bottom, rgba(0,0,0,0.2), rgba(0,0,0,0.8)), url(&quot;img/foto.jpg&quot;);	background-position: top left, right bottom;	background-size: 100%, cover;	background-repeat: repeat, repeat;	background-attachment: fixed;">
    <div class="container">
      <div class="row">
        <div class="p-5 mx-auto mx-md-0 ml-md-auto col-10 col-md-9">
          <h3 class="display-3 text-light" style=""><i class="fa fa-eercast"></i>WAWE</h3>
          <p class="mb-3 lead text-light">Of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents.</p>
          <form class="form-inline d-flex justify-content-end" method = "GET">
            <div class="input-group"> <input type="text" class="form-control" name="id_rezervace" placeholder="Vaše ID rezervace" >
              <div class="input-group-append"> <button class="btn btn-primary" >Zobrazit</button> </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

<div class = "container-fluid cerny_box">
    <?php
    include 'pohledy/dailyMenu.php';
    ?>
    &nbsp;
    
</div>