# Path to gtest root
GTEST_DIR = ./googletest/googletest

# Path to our programs
USER_DIR = .

# Flags for the preprocessor
CPPFLAGS += -isystem $(GTEST_DIR)/include

# Flags for the C++ compiler
CXXFLAGS += -g -Wall -Wextra -pthread

# Name of the tests
TESTS = tdd_tests

# Google test headers
GTEST_HEADERS = $(GTEST_DIR)/include/gtest/*.h \
								$(GTEST_DIR)/include/gtest/internal/*.h

# Build targets
